name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  unittests:
    name: Unittests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: ./main
          ref: main

      - name: Run unittests
        working-directory: ./main
        run: |
          npm install
          npm run build
          npm test
