name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  unittests:
    name: Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: ./source

      - name: Build source
        working-directory: ./source
        run: |
          npm install
          npm run build

      - name: Test source
        working-directory: ./source
        run: |
          npm test
