name: SGRUD Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pages:
    name: Pages
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: ./source

      - name: Checkout target
        uses: actions/checkout@v3
        with:
          path: ./target
          repository: sgrud/sgrud.github.io
          ssh-key: ${{secrets.PAGES_DEPLOY_KEY}}

      - name: Build source
        working-directory: ./source
        run: |
          npm install
          npm run build
          npx typedoc --out ./client
          npx jest --collectCoverage --coverageReporters html
          git --git-dir ../target/.git add -Af ./client ./coverage

      - name: Push target
        working-directory: ./target
        run: |
          git diff --cached --quiet && exit
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -m ${{github.repository}}@${{github.sha}}
          git push
